### ISSUE TITLE
Multiple points having same property (Geojson) are not getting selected.

### ISSUE THREAD

**Issue by ShenbagaRajanV** [stefanocudini/leaflet-search#131]
I have number of points having the same property (ex: status="pass"). But when I search only one marker is getting selected instead of multiple markers. How can I modify the code in order to sidentify multiple markers when searched?

**Comment by Marinko30** [comment]
Any news on this one? Same problem. Or a workaround?

**Comment by TranquilAbyss** [comment]
I am working on a solution since I have the same issue. I tried to use fuse, which is an awesome plugin,  which does not fix this problem. The problem seems to be with a Leaflet-Search source code function either `_defaultFormatData` or `_defaultFilterData` only choosing one of the markers sharing the same property value (key value).

From my testing it will use the location of the last key sharing the same value on the list. 
For example
if `list = ['a', 'b', 'c', 'd', 'e', 'a'];` then it would use the location of the last a value instead of the first.

The issue seems to occur once the source data becomes a list of records.

In the code below,

- At the line `jsons = fuse.search(text);` all the items sharing the same property are available.
- At the line where `console.log(records);` is called there is only one location assigned to the property.

```
searchControl = L.control.search({
	layer: poiLayers,
	propertyName: 'name',
	
	filterData: function(text, records) {
		var jsons, ret = {}, key;
								
		jsons = fuse.search(text);			
		console.log(records);
								
		for(var i in jsons) {
			key = jsons[i].properties.name;
			console.log(jsons[i].properties.name);
			ret[ key ]= records[key];
		}
								
		return ret;
	},
							
	moveToLocation: function(latlng, title, map) {
		var zoom = 2;
		map.setView(latlng, zoom); // access the zoom
	}
}
}).addTo(map);
```

This is all I have offer on the problem thus far. I will keep working on it and see if I can narrow down the problem. If any one else finds a solution let us know.

Thanks.

**Comment by TranquilAbyss** [comment]
In the leaflet-search source code around line 440 the json return list list which becomes the result list is created by the following code
```
_defaultFormatData: function(json) {	//default callback for format data to indexed data
	var propName = this.options.propertyName,
		propLoc = this.options.propertyLoc,
		i, jsonret = {};

	if( L.Util.isArray(propLoc) )
		for(i in json)
			jsonret[ this._getPath(json[i],propName) ]= L.latLng( json[i][ propLoc[0] ], json[i][ propLoc[1] ] );
	else
		for(i in json)
			jsonret[ this._getPath(json[i],propName) ]= L.latLng( this._getPath(json[i],propLoc) );
	//TODO throw new Error("propertyName '"+propName+"' not found in JSON data");
	return jsonret;
},
```
`jsonret[ this._getPath(json[i],propName) ] = ` Is the line that only allow one of each property name. 

I haven't tried it yet but I would suggest writing a custom formatData similar to the filterData in my last post. It may look something like this...
```
 formatData: function(json) {
	var propName = this.options.propertyName,
		propLoc = this.options.propertyLoc,
		i, jsonret = {};
			
		for(i in json)
			//create the jsonret list like the source code above;
		
	return jsonret;
},
```

I'm thinking about creating a counter to give each name in the `jsonret ` array a unique name. First I'm going to learn more about using keys in JS and the expected format from leaflet-search.

The custom formatData in the search initialization should overwrite the default formatData.

It would help if the documentation was improved to explanation the input, output, and purpose of each function and the variables were defined in a comment or readme somewhere. It took a lot of digging to figure out that the tool to make this change was already available.

Hope this helps.

**Comment by TranquilAbyss** [comment]
Another thing to add, if the leaflet-search option called layer is used then it will not run _formatData.  

Around line 728 of the leaflet sourceCode.
```
if(this.options.layer)
{
	//TODO _recordsFromLayer must return array of objects, formatted from _formatData
	this._recordsCache = this._recordsFromLayer();

	records = this._filterData( this._input.value, this._recordsCache );

	this.showTooltip( records );

	L.DomUtil.removeClass(this._container, 'search-load');
}
```

When is this feature going to be added? 

Thanks,

**Comment by stefanocudini** [comment]
See at #104 that is a good solution waiting to implement this functionality in core code
