### ISSUE TITLE
Customizing the search 

### ISSUE THREAD

**Issue by Jonkat323** [stefanocudini/leaflet-search#173]
When selecting a feature in the search bar, is it possible for the result (in my case a polygon) to be highlighted and zoomed to, rather than the red circle that indicates the location on the map?

For my application I am using the QGIS2web plugin.

**Comment by stefanocudini** [comment]
see here and study code of examples:
https://github.com/stefanocudini/leaflet-search/blob/master/examples/geocoding-nominatim.html#L44

**Comment by Jeroen-GroeneBij** [comment]
Hi, sorry to add to this issue, but my question is exactly the same, and I don't see how your answer on 2017-08-29 helps.
You refer to the marker option, but the question is not about the marker, it is about other ways to show the result. I don't see other options in your otherwise very nice plugin to change the style of the resulting feature.
I did find your Leaflet GeoJSN selector plugin, and this one does change the style of the selected feature. How to combine those two functionalities?

Or is it possible to manually add a function highlightFeature or something like this and then call upon this function for the result of the search?
