### ISSUE TITLE
Support concurrent search using several methods

### ISSUE THREAD

**Issue by gerdint** [stefanocudini/leaflet-search#183]
For a project I'm working on we would like to do a layer search and geocoder search simultaneously. (I mentioned this request in #161 but since the functionality requested is really different I create a new issue here). This is somewhat more involved than just doing a geocoder search when there is no layer hit but the rationale is to avoid the situation where there is an unintended hit in the layer data preventing the user from getting the [intended] geocoder hit.

I have a working prototype of this where I have reworked the logic in __fillRecordsCache_ to handle this. Some of the details are hard-coded at the moment but if you would be willing to merge this kind of change the client is willing to give some time for me to clean this up and generalize it for the purpose of upstreaming the changes.

I think the main problem is to adapt the interface (the _options_ object) to accomodate the different parameters for different search methods instead of reusing the same properties for different methods as is currently done.

**Comment by ovrdc-master** [comment]
You can do something similar with the [esri-leaflet-geocoder](https://github.com/Esri/esri-leaflet-geocoder/tree/master/src) by supplying multiple query providers in the options. It might be useful to look at their code to see if there is anything that would be useful here.

**Comment by tger** [comment]
Well, I have already implemented what I need. My question is whether you would like to take _leaflet-search_ in this direction and would be willing to merge code implementing this. I have implemented what is needed as I outlined in #184.

**Comment by stefanocudini** [comment]
I look patiently with a your contribution with a PR, it will be included immediately if the code works ^_^

**Comment by fenech** [comment]
@tger I am also interested in this feature - it would be great to see what you have got so far and work on getting it merged.

**Comment by tger** [comment]
This topic came up with a discussion with the client again today and they are still willing to give me some time to do this. I hope to be able to submit a PR in the following month.

**Comment by stefanocudini** [comment]
@tger it would be nice

**Comment by tger** [comment]
Hello.

I've put the changes on a branch here: https://github.com/tger/leaflet-search/tree/concurrent-geocoding (diff: https://github.com/stefanocudini/leaflet-search/compare/a83cd095aa761b992b2dff263e38f1c113abe124...tger:concurrent-geocoding)

Unfortunately the client have been prioritizing other things so I haven't been able to rebase the code and clean up the code like I wanted, hence the code drop and instead of a proper PR. The commit above contains some other fixes (I suspect most of them are still relevant, but haven't verified against master). Initially there was also a Google Maps geocoder config option but it was removed in favor of OSM and MapQuest, should be easy to add though.

So, while not so pretty my summer holidays are starting today and since I wanted this to get out of the door in June here it is.
