### ISSUE TITLE
scroll problem on search results with firefox

### ISSUE THREAD

**Issue by pouemes** [stefanocudini/leaflet-search#299]
take this example with leaflet-search 3.02
https://opengeo.tech/maps/leaflet-search/examples/geojson-layer.html
replace https://unpkg.com/leaflet@1.3.0/dist/leaflet.css and https://unpkg.com/leaflet@1.3.0/dist/leaflet.js
by leaflet version 1.7.1 or 1.8.0

search for m then try to scroll on the result, if it work with chrome edge and opera, it doen't work with firefox
pehaps someone could understand why?

**Comment by Falke-Design** [comment]
This is a issue with the plugin / Firefox, because it uses the old [mousewheel](https://github.com/stefanocudini/leaflet-search/blob/15b4c295c935c6c227781fca05c6a6daa113c621/src/leaflet-search.js#L362) event listener instead of  `wheel` to prevent zooming on the map. Firefox doesn't fire `mousewheel` anymore: https://plnkr.co/edit/sbrPjG2j2GRJ3Av0

You use this simple workaround:
```
 your code ....
// adding the controller to the map
map.addControl( searchControl ); // or searchControl.addTo(map);

// disable zoom scrolling in the search container
L.DomEvent.disableScrollPropagation(searchControl.getContainer());
```

**Comment by pouemes** [comment]
or in eaflet-search.src.js
line 318 replace `.on(tool, 'mousewheel', function(e) {` by `.on(tool, 'wheel', function(e) {`
