### ISSUE TITLE
recursive search

### ISSUE THREAD

**Issue by Sekulidan** [stefanocudini/leaflet-search#95]
Hi,
I use this plugin to search on multible layers so I put all those layers in some layer group and tried to hand this layerGroup over to the plugin.

But the plugin is only searching for GeoJSON stuff in instanceof L.LayerGroup.

I modified the implementation and call of _recordsFromLayer(..) for a diff check the appending code relative to v1.8.4

(.js renamed as .txt for upload)
[leaflet-search.src - recursive.txt](https://github.com/stefanocudini/leaflet-search/files/47045/leaflet-search.src.-.recursive.txt)

Greetings: Sekulidan

PS this is related to [Search on the active Layer](https://github.com/stefanocudini/leaflet-search/issues/51) because I use a LayerGroup where I add a subset of the current overlay layers

**Comment by ghybs** [comment]
This issue on GIS Stack Exchange is due to Leaflet Search not properly managing vector shapes in nested GeoJSON Layer Groups (if `layer` option is passed a Layer Group that itself contains GeoJSON Layer Groups with shapes, or it can even be deeper nesting):
https://gis.stackexchange.com/questions/175863/adding-one-search-box-for-multiple-geojson-polygon-layers

In `_recordsFromLayer`, when sub-layer is a Layer Group, the method does not recurs on itself, but instead does a "degraded" search that [needs `getLatLng`](https://github.com/stefanocudini/leaflet-search/blob/master/src/leaflet-search.js#L520). Hence it can only manage point data (markers) in nested Layer Groups.

**Comment by stefanocudini** [comment]
see it #171
